apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-node
  namespace: redis-standalone
  labels:
    app: redis-node

spec:
  replicas: 1
  selector:
    app: redis-node

  template:
    metadata:
      labels:
        app: redis-node
    spec:
      containers:
      - name: redis-node
        image: oberthur/docker-redis:4.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: "REDIS_NODE_TYPE"
          value: "STANDALONE"
        - name: "REDIS_CONFIG"
          value: |
            appendonly no
        ports:
        - name: redis-port
          containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          timeoutSeconds: 5